// <auto-generated />
namespace TestTaskVirusBlock.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CarsAddedModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CarsAddedModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202106121736207_CarsAddedModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
